### ISSUE TITLE
Getting error "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by masgari** [wavefrontHQ/wavefront-fargate-collector#2]
Hi
I am using latest image and get this error in CW logs:
```
panic: runtime error: index out of range
goroutine 1 [running]:
main.main()
/Users/vikramr/dev/go/src/github.com/wavefronthq/wavefront-fargate-collector/adapter.go:50 +0x9e4
```

My container spec:
```
         - Name: wf-metrics-collector # https://docs.wavefront.com/integrations_aws_ecs.html
            Image: wavefronthq/wavefront-fargate-collector:latest # https://github.com/wavefrontHQ/wavefront-fargate-collector
            Cpu: 256
            Memory: 512
            Essential: false
            PortMappings:
              - ContainerPort: 8000
                HostPort: 8000
                Protocol: TCP
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: 
                  Ref: ContainerLogGroup
                awslogs-region: eu-west-1
                awslogs-stream-prefix: "metrics-collector"    
            Command:
              - "-debug"
              - "-port=8000"
              - "-storage_driver=wavefront"
              - "-storage_driver_options=\"metric_flush_interval=10 storage_driver_wf_proxy_host=wavefront.product.internal storage_driver_wf_metric_prefix=product.${self:provider.stage}.service.fargate. \""
```
